name: Lint shell scripts
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install shfmt and fd
        run: |
          sudo snap install shfmt

      - name: Linting with shfmt and shellcheck
        run: |
          find . -type f \( -executable -or -name "*.sh" \) -not -path "./.git/*" -print0 |
              while IFS= read -r -d '' file; do
                  shellcheck -s bash -e SC1090,SC1091 "$file"
                  shfmt -d -ci -i 4 "$file"
              done

