name: Lint Scripts
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo snap install shfmt
      - name: Run lint.sh
        run: bash lint.sh
