name: Lint shell scripts
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install shfmt and fd
        run: |
          sudo snap install shfmt
          sudo apt-get install fd-find

      - name: Linting with shfmt and shellcheck
        run: |
          for i in $(fdfind -t x -E etc -E config); do
            shellcheck -s bash -e SC1090,SC1091 "$i"
            shfmt -d -ci -i 4 "$i"
          done
